// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anzshudrrpupcqmzjrqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuenNodWRycnB1cGNxbXpqcnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDU3MTgsImV4cCI6MjA2MDYyMTcxOH0.u0M94dKGXdXPi4_kV2h5osWTeAZfmcUmWd6KAjhQAMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);